hosts:
  ibm1:
    type: aix
    host: 10.62.36.3
    user: root
    pass: root
  hp1:
    type: hp-ux
    host: 10.62.36.23
    user: root
    pass: root
  switch:
    type: brocade
    host: 10.32.32.199
    user: admin
    pass: password