hosts:
  ibm1:
    type: aix
    host: 10.62.36.3
    user: root
    pass: root
  hp23:
    type: hp-ux
    host: 10.62.36.23
    user: root
    pass: root
  hp22:
    type: hp-ux
    host: 10.62.36.22
    user: root
    pass: root
  bottom:
    type: brocade
    host: 10.32.32.199
    user: admin
    pass: password
  top:
    type: brocade
    host: 10.32.32.198
    user: admin
    pass: password